### ISSUE TITLE
File Not Found libmysql.lib

### ISSUE THREAD

**Issue by netmou** [huntlabs/hunt-skeleton#2]
PS H:\> git clone https://github.com/huntlabs/hunt-skeleton.git myproject
Cloning into 'myproject'...
remote: Counting objects: 387, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 387 (delta 19), reused 45 (delta 11), pack-reused 324
Receiving objects: 100% (387/387), 3.11 MiB | 22.00 KiB/s, done.
Resolving deltas: 100% (124/124), done.
PS H:\> cd myproject
PS H:\myproject> dub run
Fetching libmemcached 1.1.1 (getting selected version)...
Fetching collie 0.10.15 (getting selected version)...
Fetching kiss 0.4.4 (getting selected version)...
Fetching hunt 1.1.0 (getting selected version)...
Fetching cache 0.0.6 (getting selected version)...
Fetching entity 1.5.1 (getting selected version)...
Fetching database 0.1.4 (getting selected version)...
Fetching rocksdb 0.0.7 (getting selected version)...
Fetching dredis 0.0.9 (getting selected version)...
Performing "debug" build using D:\Program Files\dlang\dmd2\windows\bin\dmd.exe for x86.
dredis 0.0.9: building configuration "library"...
kiss 0.4.4: building configuration "default"...
cache 0.0.6: building configuration "default"...
collie 0.10.15: building configuration "default"...
database 0.1.4: building configuration "mysql"...
entity 1.5.1: building configuration "default"...
hunt 1.1.0: building configuration "default"...
node name: hunt
hunt-skeleton ~master: building configuration "application"...
Linking...
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
libmysql.lib
 Warning 2: File Not Found libmysql.lib
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_close@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_set_character_set@8
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_real_connect@32
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_init@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_query@8
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_get_client_info@0
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_error@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_ping@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_thread_id@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_insert_id@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_affected_rows@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_store_result@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(connection)
 Error 42: Symbol Undefined _mysql_real_escape_string@16
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_free_result@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_num_rows@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_num_fields@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_fetch_lengths@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_fetch_row@4
C:\Users\leiya\AppData\Local\dub\packages\database-0.1.4\database\.dub\build\mysql-debug-windows-x86-dmd_2080-19CEB98691975FCD7F90C3052A53F137\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_fetch_fields@4
Error: linker exited with status 19
D:\Program Files\dlang\dmd2\windows\bin\dmd.exe failed with exit code 1.

**Comment by zoujiaqing** [comment]
Windows platform only support 64-bit, You can set it for dub:
```shell
dub run --arch=x86_64
```

PS: before you need install Windows SDK
