### ISSUE TITLE
能不能简化一下依赖关系

### ISSUE THREAD

**Issue by Domain** [huntlabs/hunt-skeleton#6]
作为一个框架的例子，依赖太多东西了，特别是libmysqlclient，我是在android用 termux和ldc编译的，但是termux没有libmysqlclient，跑不起来

**Comment by zoujiaqing** [comment]
其实这个我们也讨论过，但是一个 web 框架连接数据库需要额外配置也不太明智，当然我们可以使用 lite 形式来简化项目依赖进行快速构建，你有啥好想法？

**Comment by Domain** [comment]
类似于vibe.d那样，每个功能模块化，每个模块都有单独的例子，再加上几个综合的例子，会方便很多。

**Comment by zoujiaqing** [comment]
我们都是分项目走的，现在 huntlabs 的项目大概也有 20 多个了，所以没有放在一个统一目录中。

hunt framework 也是最大的一个项目，所以整合了所有框架和库。

其实这么全也是为了小白用户能够跑起来不配置啥都能干，像高手就喜欢用最精简的，有需要就自己往里加依赖。

至于 vibe.d 来说它仅仅是一库，还算不上是框架，所以可以这么干。

现在我么的项目越来越稳定了，接下来会有更丰富的示例代码和文档。

**Comment by Heromyth** [comment]
The drivers in hunt-database have been implemented in D. The whole Hunt-Framework is nearly implemented in D, except for hunt-openssl which depends on OpenSSL.
