### ISSUE TITLE
windows下面编译失败

### ISSUE THREAD

**Issue by ikvm** [huntlabs/hunt-skeleton#7]
win7-x64/dmd-2.087.1

lld-link: error: could not open libcmt.lib: no such file or directory
lld-link: error: could not open OLDNAMES.lib: no such file or directory
Error: linker exited with status 1
FAIL .dub\build\application-debug-windows-x86_64-dmd_2087-4DF767B3D0454A9F4CF269B185825446\ hunt-skeleton executable

**Comment by ikvm** [comment]
dub.sdl增加配置

lflags "\"C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\lib\""

Error: module `Files` is in file 'Files.d' which cannot be read
import path[0] = D:\dmd-2.087.1\windows\bin\..\..\src\phobos
import path[1] = D:\dmd-2.087.1\windows\bin\..\..\src\druntime\import
FAIL .dub\build\application-debug-windows-x86_64-dmd_2087-58CDB765F4E571D9DF05C03C8C662FD0\ hunt-skeleton executable

**Comment by Heromyth** [comment]
Install DMD on Windows correctly. Here is an article: https://blog.csdn.net/smartly/article/details/103198287.
